project:
  type: website

website:
  title: "GISProject"
  navbar:
    left:
      - href: overview.qmd
        text: Overview
      - href: methodology.qmd
        text: Methodology
      - href: findings.qmd
        text: Results & Discussion
      - href: analysis.qmd
        text: Analysis

        
    right:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Project Schedule

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

