project:
  type: website

website:
  title: "G2 Team 7: Ex-Schools Me!"
  navbar:
    left:
      - href: overview.qmd
        text: Overview
      - href: methodology.qmd
        text: Methodology
      - href: analysis.qmd
        text: Results & Analysis
      - href: findings.qmd
        text: Lesson Learnt
      - href: poster.qmd
        text: Poster


        
    right:
      - href: index.qmd
        text: Home


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

