---
title: "G2 TEAM7"
---

Welcome to our GIS Project web site. Our group is working on Theme 2: Geography of Accessibility with GIS-based Network Analysis and on specific sub-theme 1: Impact of closures or mergers of education institutions on equity of access.

## Data Used:

The data used are as follows:

-   Data.gov (School Directory and Information 24 March Year 2021)

Additional Data Created:

-   Created additional CSV files to input all mergers of different years, merged schools in Year 2019 and future merges Year 2022 - Year 2024

## Scope of work:

The scope of work are as follows:

## Delegation of work:

We delegate the roles equally among the 3 of us such that 2 people will be in charge of the QGIS (Edlyn & Beatrice), 3 of us to do posters and report together, 1 person to handle the webpage (Shu Ying). We decided to have this allocation so that all of us can focus on different areas and we can complete the work productively. Even so, all of us are still involved in all of the segments as we meet regularly to complete the project as a team.

| Job Scope                                                              | Person-In-Charge |
|------------------------------------------------------------------------|------------------|
| Selection of project focus and conducting literature review            | Team             |
| Performing GIS analysis                                                | Team             |
|  Project Report                                                        | Team             |
| Data collection, extraction, integration, transformation and wrangling | Edlyn & Beatrice |
| Designing and building GIS model and database                          | Edlyn & Beatrice |
| Preparing Poster                                                       | Beatrice         |
| Project Minutes                                                        | Shu Ying         |
| Project Website                                                        | Shu Ying         |

-   For every updates we have as a team, Shu Ying will make changes on this webpage, commit and push it at the end of the day

-   Our team have also created a slack group and connected slack with Github so that all members are aware that for every pushes as we will receive updates

## Project Links:

Our Github Link: <https://github.com/ShuYing0506/GISProject>

Setting up Netlify: <https://app.netlify.com/sites/smtgroup7/settings/domain>

Slack workspace: <https://smt201group7.slack.com>
