---
title: ""
editor: visual
---

# **Overview**

## **Delegation of work:**

We delegate the roles equally among the 3 of us such that 2 people will be in charge of the QGIS (Edlyn & Beatrice), 3 of us to do posters and report together, 1 person to handle the webpage (Shu Ying). We decided to have this allocation so that all of us can focus on different areas and we can complete the work productively. Even so, all of us are still involved in all of the segments as we meet regularly to complete the project as a team.

| Job Scope                                                              | Person-In-Charge |
|------------------------------------------------------------------------|------------------|
| Selection of project focus and conducting literature review            | Team             |
| Performing GIS analysis                                                | Team             |
|  Project Report                                                        | Team             |
| Data collection, extraction, integration, transformation and wrangling | Edlyn & Beatrice |
| Designing and building GIS model and database                          | Edlyn & Beatrice |
| Preparing Poster                                                       | Beatrice         |
| Project Minutes                                                        | Shu Ying         |
| Project Website                                                        | Shu Ying         |

| Data Collection and V isualisation | Person-In-Charge |
|------------------------------------|------------------|
| Primary School                     | Edlyn            |
| Secondary School                   | Beatrice         |
| Post-Secondary School              | Beatrice         |
| Transport Analysis                 | Beatrice         |

-   For every updates we have as a team, Shu Ying will make changes on this webpage, commit and push it at the end of the day

-   Our team have also created a slack group and connected slack with Github so that all members are aware that for every pushes as we will receive updates

## **Sources of Data:**

The data used are as follows:

-   Data.gov.sg

-   LTA Datamall

-   Open Street Map

-   Google

## **Literature Review**

In this project, the following articles are reviewed to help us in understanding the mergers.

-   <https://www.straitstimes.com/singapore/education/2019-school-mergers-7-things-to-know>

-   <https://www.channelnewsasia.com/singapore/moe-schools-merging-new-town-tanglin-telok-kurau-201401>

-   <https://www.straitstimes.com/singapore/education/school-mergers-2019-why-were-the-8-government-jcs-the-ones-selected-for-merger>

-   <https://www.gov.sg/article/why-is-the-ministry-of-education-merging-some-schools>

-   <https://guidesify.com/merger-of-jcs-singapore/>

## 
